# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test  
      - uses: codecov/codecov-action@v1
  update-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run docs  
      - run: |
          git config --global user.name 'Sharon (Sean) Rolel'
          git config --global user.email 'srolel@users.noreply.github.com'
          git commit -am "Automatic docs update"
          git push
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: install, build and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          PUBLISHED_VERSION=$(npm show message-rpc version)
          CURRENT_VERSION=$(node --eval="process.stdout.write(require('./package.json').version)")
          if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
              echo "Version $CURRENT_VERSION already published."
          else
              echo "Publishing $CURRENT_VERSION"
              npm install
              npm build
              npm publish
          fi
